name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: install node packages
        run: |
          npm install
      - name: lint the code
        run: |
          npm run eslint

      - name: build
        run: |
          npm run build
        env:
          PORT: 5000

      - name: test
        run: |
          npm run test

      - name: cypress tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - if: ${{ github.event_name == 'push' }}
        name: deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "glacial-thicket-33219"
          heroku_email: "hadyelzayady@yahoo.com"
          healthcheck: "https://glacial-thicket-33219.herokuapp.com/health"
          rollbackonhealthcheckfailed: true

      - if: ${{ github.event_name == 'push' }}
        name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
